name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: 0.15.7
  url_launcher: 3.0.3
  json_annotation: 2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter packages pub run build_runner build
#flutter packages pub run build_runner watch 后台监控有变化自动执行

  build_runner: 1.1.2
  json_serializable: 2.0.1
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - lib/example_code.dart
      - assets/flutter-mark-square-64.png
      - assets/logo_small.png
      - assets/india_chettinad_silk_market.png
      - assets/square/ali.png
      - assets/square/peter.png
      - assets/square/sandra.png
      - assets/square/stella.png
      - assets/square/trevor.png
      - assets/square/ali_landscape.png
      - assets/products/backpack.png
      - assets/products/belt.png
      - assets/products/cup.png
      - assets/products/deskset.png
      - assets/products/dress.png
      - assets/products/earrings.png
      - assets/products/flatwear.png
      - assets/products/hat.png
      - assets/products/jacket.png
      - assets/products/jumper.png
      - assets/products/kitchen_quattro.png
      - assets/products/napkins.png
      - assets/products/planters.png
      - assets/products/platter.png
      - assets/products/scarf.png
      - assets/products/shirt.png
      - assets/products/sunnies.png
      - assets/products/sweater.png
      - assets/products/sweats.png
      - assets/products/table.png
      - assets/products/teaset.png
      - assets/products/top.png
      - assets/places/india_chennai_flower_market.png
      - assets/places/india_thanjavur_market.png
      - assets/places/india_tanjore_bronze_works.png
      - assets/places/india_tanjore_market_merchant.png
      - assets/places/india_tanjore_thanjavur_temple.png
      - assets/places/india_pondicherry_salt_farm.png
      - assets/places/india_chennai_highway.png
      - assets/places/india_chettinad_silk_maker.png
      - assets/places/india_tanjore_thanjavur_temple_carvings.png
      - assets/places/india_chettinad_produce.png
      - assets/places/india_tanjore_market_technology.png
      - assets/places/india_pondicherry_beach.png
      - assets/places/india_pondicherry_fisherman.png
      - assets/animated_flutter_stickers.webp
      - assets/animated_flutter_lgtm.gif

      - assets/food/butternut_squash_soup.png
      - assets/food/cherry_pie.png
      - assets/food/chopped_beet_leaves.png
      - assets/food/pesto_pasta.png
      - assets/food/roasted_chicken.png
      - assets/food/spanakopita.png
      - assets/food/spinach_onion_salad.png
      - assets/food/icons/fish.png
      - assets/food/icons/healthy.png
      - assets/food/icons/main.png
      - assets/food/icons/meat.png
      - assets/food/icons/quick.png
      - assets/food/icons/spicy.png
      - assets/food/icons/veggie.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
